### PR TITLE
Update to 9.0.1

### PR DESCRIPTION
**Pull request by cekees**
regro-cf-autotick-bot doesn't seem to be running so I'm bumping to 9.0.1 release manually
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by cekees** [comment]
@conda-forge-admin, please rerender

**Comment by cekees** [comment]
@conda-forge-admin, please rerender

**Review by cekees — COMMENTED** [review]
@SylvainCorlay I think this is good enough. Doesn't look like anybody has been maintaining the feedstock, so it was several releases behind.  Likely could be improved with options to support the OpenMP, TBB, and CUDA options in chrono.

**Comment by traversaro** [comment]
Are you interested in being a mantainer here? See https://github.com/conda-forge/pychrono-feedstock/pull/34 . fyi @wolfv

**Comment by cekees** [comment]
> Are you interested in being a mantainer here? See #34 . fyi @wolfv

Sure, I can help from time to time. We really need one of the chrono developers on this.

**Comment by wolfv** [comment]
Thank you @cekees!

**Pull request merged**
